image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

stages:
  - install
  - test
  - build
  - deploy

install_dependencies:
  stage: install
  script:
    - npm ci

test:frontend:
  stage: test
  script:
    - npm run test --workspace frontend

test:backend:
  stage: test
  script:
    - npm run test --workspace backend

build:frontend:
  stage: build
  script:
    - npm run build --workspace frontend
  artifacts:
    paths:
      - frontend/build

deploy:frontend:
  stage: deploy
  script:
    - sshpass -V
    - export SSHPASS=vagrant
    - sshpass -e scp -o stricthostkeychecking=no -r frontend/build/* vagrant@192.168.56.10:/var/www/html

deploy:backend:
  stage: deploy
  script:
    - sshpass -V
    - export SSHPASS=vagrant
    - sshpass -e scp -o stricthostkeychecking=no -r backend/* vagrant@192.168.56.10:/var/www/express
    - sshpass -e scp -o stricthostkeychecking=no -r backend/.env.production vagrant@192.168.56.10:/var/www/express/.env
    - sshpass -e ssh vagrant@192.168.56.10 "cd /var/www/express && npm install && pm2 restart index"