image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - build

install_dependencies:
  stage: install
  script:
    - npm ci

test:frontend:
  stage: test
  script:
    - npm run test --workspace frontend

test:backend:
  stage: test
  script:
    - npm run test --workspace backend

build:frontend:
  stage: build
  script:
    - npm run build --workspace frontend
  artifacts:
    paths:
      - frontend/build